//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEnabledDataSet_Output", Namespace="http://schemas.datacontract.org/2004/07/FDIWebServices")]
    public partial class GetEnabledDataSet_Output : object
    {
        
        private string CodEsitoField;
        
        private string DescEsitoField;
        
        private ServiceReference1.SetDati[] SetDatiAbilitatiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEsito
        {
            get
            {
                return this.CodEsitoField;
            }
            set
            {
                this.CodEsitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEsito
        {
            get
            {
                return this.DescEsitoField;
            }
            set
            {
                this.DescEsitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SetDati[] SetDatiAbilitati
        {
            get
            {
                return this.SetDatiAbilitatiField;
            }
            set
            {
                this.SetDatiAbilitatiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetDati", Namespace="http://schemas.datacontract.org/2004/07/FDIWebServices")]
    public partial class SetDati : object
    {
        
        private string DescriptionField;
        
        private string KeyField;
        
        private int SchemaCodeField;
        
        private string UrlNewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SchemaCode
        {
            get
            {
                return this.SchemaCodeField;
            }
            set
            {
                this.SchemaCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlNews
        {
            get
            {
                return this.UrlNewsField;
            }
            set
            {
                this.UrlNewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSchemaDataSet_Output", Namespace="http://schemas.datacontract.org/2004/07/FDIWebServices")]
    public partial class GetSchemaDataSet_Output : object
    {
        
        private string CodEsitoField;
        
        private string DescEsitoField;
        
        private ServiceReference1.Field[] FieldsField;
        
        private int SchemaCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEsito
        {
            get
            {
                return this.CodEsitoField;
            }
            set
            {
                this.CodEsitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEsito
        {
            get
            {
                return this.DescEsitoField;
            }
            set
            {
                this.DescEsitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Field[] Fields
        {
            get
            {
                return this.FieldsField;
            }
            set
            {
                this.FieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SchemaCode
        {
            get
            {
                return this.SchemaCodeField;
            }
            set
            {
                this.SchemaCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Field", Namespace="http://schemas.datacontract.org/2004/07/FDIWebServices")]
    public partial class Field : object
    {
        
        private string DescriptionField;
        
        private int IdNumField;
        
        private string KeyField;
        
        private string LengthField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNum
        {
            get
            {
                return this.IdNumField;
            }
            set
            {
                this.IdNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDataSet_Output", Namespace="http://schemas.datacontract.org/2004/07/FDIWebServices")]
    public partial class GetDataSet_Output : object
    {
        
        private byte[] ByteListFileField;
        
        private string CodEsitoField;
        
        private string DescEsitoField;
        
        private string OutputValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ByteListFile
        {
            get
            {
                return this.ByteListFileField;
            }
            set
            {
                this.ByteListFileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEsito
        {
            get
            {
                return this.CodEsitoField;
            }
            set
            {
                this.CodEsitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEsito
        {
            get
            {
                return this.DescEsitoField;
            }
            set
            {
                this.DescEsitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputValue
        {
            get
            {
                return this.OutputValueField;
            }
            set
            {
                this.OutputValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDataSetChanges_Output", Namespace="http://schemas.datacontract.org/2004/07/FDIWebServices")]
    public partial class GetDataSetChanges_Output : object
    {
        
        private byte[] ByteListFileField;
        
        private string CodEsitoField;
        
        private string DescEsitoField;
        
        private int NumRecordsField;
        
        private string OutputValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ByteListFile
        {
            get
            {
                return this.ByteListFileField;
            }
            set
            {
                this.ByteListFileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEsito
        {
            get
            {
                return this.CodEsitoField;
            }
            set
            {
                this.CodEsitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEsito
        {
            get
            {
                return this.DescEsitoField;
            }
            set
            {
                this.DescEsitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumRecords
        {
            get
            {
                return this.NumRecordsField;
            }
            set
            {
                this.NumRecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputValue
        {
            get
            {
                return this.OutputValueField;
            }
            set
            {
                this.OutputValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.farmadati.it", ConfigurationName="ServiceReference1.FarmadatiItaliaWebServicesM2")]
    public interface FarmadatiItaliaWebServicesM2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetEnabledDataSet", ReplyAction="http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetEnabledDataSetRes" +
            "ponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetEnabledDataSet_Output> GetEnabledDataSetAsync(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetSchemaDataSet", ReplyAction="http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetSchemaDataSetResp" +
            "onse")]
        System.Threading.Tasks.Task<ServiceReference1.GetSchemaDataSet_Output> GetSchemaDataSetAsync(string Username, string Password, string CodiceSetDati, bool TracciatoVar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetDataSet", ReplyAction="http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetDataSetResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetDataSet_Output> GetDataSetAsync(string Username, string Password, string CodiceSetDati, string Modalita, int PageN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetDataSetChanges", ReplyAction="http://webservices.farmadati.it/FarmadatiItaliaWebServicesM2/GetDataSetChangesRes" +
            "ponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetDataSetChanges_Output> GetDataSetChangesAsync(string Username, string Password, string CodiceSetDati, string DataIstanza, string Modalita, int PageN, int PagingN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface FarmadatiItaliaWebServicesM2Channel : ServiceReference1.FarmadatiItaliaWebServicesM2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class FarmadatiItaliaWebServicesM2Client : System.ServiceModel.ClientBase<ServiceReference1.FarmadatiItaliaWebServicesM2>, ServiceReference1.FarmadatiItaliaWebServicesM2
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FarmadatiItaliaWebServicesM2Client() : 
                base(FarmadatiItaliaWebServicesM2Client.GetDefaultBinding(), FarmadatiItaliaWebServicesM2Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_FarmadatiItaliaWebServicesM2.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FarmadatiItaliaWebServicesM2Client(EndpointConfiguration endpointConfiguration) : 
                base(FarmadatiItaliaWebServicesM2Client.GetBindingForEndpoint(endpointConfiguration), FarmadatiItaliaWebServicesM2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FarmadatiItaliaWebServicesM2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FarmadatiItaliaWebServicesM2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FarmadatiItaliaWebServicesM2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FarmadatiItaliaWebServicesM2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FarmadatiItaliaWebServicesM2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetEnabledDataSet_Output> GetEnabledDataSetAsync(string Username, string Password)
        {
            return base.Channel.GetEnabledDataSetAsync(Username, Password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetSchemaDataSet_Output> GetSchemaDataSetAsync(string Username, string Password, string CodiceSetDati, bool TracciatoVar)
        {
            return base.Channel.GetSchemaDataSetAsync(Username, Password, CodiceSetDati, TracciatoVar);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDataSet_Output> GetDataSetAsync(string Username, string Password, string CodiceSetDati, string Modalita, int PageN)
        {
            return base.Channel.GetDataSetAsync(Username, Password, CodiceSetDati, Modalita, PageN);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDataSetChanges_Output> GetDataSetChangesAsync(string Username, string Password, string CodiceSetDati, string DataIstanza, string Modalita, int PageN, int PagingN)
        {
            return base.Channel.GetDataSetChangesAsync(Username, Password, CodiceSetDati, DataIstanza, Modalita, PageN, PagingN);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_FarmadatiItaliaWebServicesM2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_FarmadatiItaliaWebServicesM2))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices-farmadati.dyndns.ws/WS2/FarmadatiItaliaWebServicesM2.svc");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FarmadatiItaliaWebServicesM2Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_FarmadatiItaliaWebServicesM2);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FarmadatiItaliaWebServicesM2Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_FarmadatiItaliaWebServicesM2);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_FarmadatiItaliaWebServicesM2,
        }
    }
}
